### ISSUE TITLE
Error when calling `/c/exchange/<exchange_name>/status` after upgrade to HMA 1.1.1

### ISSUE THREAD

**Issue by gdubicki** [facebook/ThreatExchange#1933]
Since the upgrade from HMA to 1.0.21 to 1.1.1 we are getting error on calls to `/c/exchange/<exchange_name>/status`, which worked correctly before.

Stacktrace:

```
[2026-02-18 14:13:47,733] ERROR in app: Exception on /c/exchange/<REDACTED>/status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: exchange_get_fetch_status() got an unexpected keyword argument 'exchange_name'
```
