### PR TITLE
[hma] Fix lookup with dist

### LINKED ISSUE #1766: [hma] unable to lookup a video_md5 hashes after distance was added to m/lookup
to reproduce:
- get a video_md5 hash
- try to look it up (m/lookup?signal=<hash>&signal_type=video_md5)
- error:
```
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/OpenMediaMatch/blueprints/matching.py", line 221, in lookup_get
    resp = lookup(signal, signal_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/OpenMediaMatch/blueprints/matching.py", line 284, in lookup
    "distance": match.similarity_info.distance,
AttributeError: 'SignalSimilarityInfo' object has no attribute 'distance'
```

relevant PR: https://github.com/facebook/ThreatExchange/pull/1738

### PR DESCRIPTION
**Pull request by Dcallies**
Summary
---------

A prior PR accidentally used the wrong distance API, and the type checker couldn't tell, likely due to the number of generics used along the way.

The real villain here is the lack of comprehensive testing on the lookup APIs, which I made the start of here.

Fixes #1766

Test Plan
---------

Added regression test, breaks before with the stack trace from #1766, works after.

### CODE REVIEW

File: hasher-matcher-actioner/src/OpenMediaMatch/tests/test_api.py [hunk 1]
```diff
@@ -81,7 +85,7 @@ def test_exchange_api_set_auth(app: Flask, client: FlaskClient):
     tx_name = FBThreatExchangeSignalExchangeAPI.get_name()
     # Monkeypatch installed types
     storage.exchange_types = {  # type:ignore
-        api_cls.get_name(): api_cls
+        api_cls.get_name(): api_cls  # type:ignore
```
Comment (Dcallies) [inline hasher-matcher-actioner/src/OpenMediaMatch/tests/test_api.py:88]:
```suggestion
        api_cls.get_name(): api_cls
```
